################################################################
#
# This is the configurable part of the Makefile.
# It must be named 'Makefile.config'.
#
#
################################################################

################
#
# Define the OS to compile for and the compiler to use.

OS = Linux

C++ = g++32

################
#
# Define the C++ compiler flags

C++FLAGS = -g -Wall

######### Others
OTHERINC = -I../include
OTHERLIB = -L../lib -lm 
